# Generated by Django 5.2.7 on 2025-10-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0001_initial"),
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="product_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_medias",
                to="core_app.media",
            ),
        ),
    ]
