# Generated by Django 5.2.7 on 2025-10-22 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order_app", "0001_initial"),
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_order_items",
                to="product_app.product",
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="methods",
                to="order_app.shippingcompany",
                verbose_name="شرکت ارسال\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_shipping_methods",
                to="order_app.shippingmethod",
            ),
        ),
    ]
