# Generated by Django 5.2.7 on 2025-10-22 09:53

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("category_name", models.CharField(db_index=True, max_length=255)),
                ("category_slug", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("description_slug", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "blog_category",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="PostBlogLikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "db_table": "post_blog_likes",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="TagBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tag_name", models.CharField(db_index=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "blog_tag",
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="PostBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("post_title", models.CharField(max_length=255)),
                ("post_slug", models.SlugField(allow_unicode=True, max_length=500)),
                ("post_body", django_ckeditor_5.fields.CKEditor5Field()),
                ("read_time", models.PositiveSmallIntegerField()),
                ("likes", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("description_slug", models.TextField(blank=True, null=True)),
                (
                    "post_introduction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        related_name="post_authors", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="blog_posts", to="blog_app.categoryblog"
                    ),
                ),
            ],
            options={
                "db_table": "blog_post",
                "ordering": ("-id",),
            },
        ),
    ]
