# Generated by Django 5.2.7 on 2025-10-22 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog_app", "0001_initial"),
        ("core_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="postblog",
            name="post_cover_media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blog_posts_cover_media",
                to="core_app.media",
            ),
        ),
        migrations.AddField(
            model_name="postbloglikes",
            name="post_blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="blog_app.postblog",
                verbose_name="post blog",
            ),
        ),
        migrations.AddField(
            model_name="postbloglikes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="postblog",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="post_tags", to="blog_app.tagblog"
            ),
        ),
    ]
